/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ConnectionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GlobalTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MAILGUN_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OwnerGroupTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PasskeyCredentialTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RestAPI": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SocketAPI": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "TreasureMapTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TreasureObjectTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}